spring:
  cloud:
    openfeign:
      client:
        config:
          payment:
            url: http://localhost:8765/payment
          storage:
            url: http://localhost:8765/storage

shop:
  account:
    number: 3

tmpVar: configServer
